# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RandomCircles(object):
    def setupUi(self, RandomCircles):
        RandomCircles.setObjectName("RandomCircles")
        RandomCircles.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=RandomCircles)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GenerateButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.GenerateButton.setObjectName("GenerateButton")
        self.verticalLayout.addWidget(self.GenerateButton)
        self.ImageLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.ImageLabel.setText("")
        self.ImageLabel.setScaledContents(False)
        self.ImageLabel.setObjectName("ImageLabel")
        self.verticalLayout.addWidget(self.ImageLabel)

        self.retranslateUi(RandomCircles)
        QtCore.QMetaObject.connectSlotsByName(RandomCircles)

    def retranslateUi(self, RandomCircles):
        _translate = QtCore.QCoreApplication.translate
        RandomCircles.setWindowTitle(_translate("RandomCircles", "Form"))
        self.GenerateButton.setText(_translate("RandomCircles", "Generate"))
